### PR TITLE
New Version

### PR DESCRIPTION
**Pull request by Mr-7mdan**
I had to request a merge to an issue with github not recognizing filename case sensitivity changes

### CODE REVIEW

**Comment by zombiB** [comment]
I guess u should sync your repo before pulling your request, in github desktop u can refresh the repo first or try to clone the matrix repo

**Comment by Mr-7mdan** [comment]
@zombiB it is synced

but I think the fork we created before is causing some issues.

take some screenshots and show me how pls

**Review by zombiB — APPROVED** [review]

**Comment by qusai900** [comment]
مشكووووور

**Comment by qusai900** [comment]
Great effort

**Comment by qusai900** [comment]
Thank you very much

**Pull request merged**
