### PR TITLE
Many Updates 

### PR DESCRIPTION
**Pull request by Mr-7mdan**
- I created icons themes for this addon. Now the user can choose what theme to use.
image

- I create a Modern Icons set for Matrix. (You still can select the old icons if your prefer the old design)
image
image

Main Menu:
image
image

Movies:
image

TV Shows:
image

High Quality Posters:
image

-  I did multiple changes to Akwam, Al fajer tv, arabseed in order to get high quality posters for Movies, TV Shows, and Episodes.
- I fixed Arabseed, faselHD sites.

### CODE REVIEW

**Comment by mohamedsaad208** [comment]
Is it applicable to installed as different plug-in

**Comment by zombiB** [comment]
thank u good job

**Comment by mohamedsaad208** [comment]
Who can I apply this them ?

**Comment by mohamedsaad208** [comment]
Who can I apply this new theme?

**Comment by Mr-7mdan** [comment]
> Who can I apply this new theme?

The owner of the addon Zombib merged the changes to the original repo. Now, you should an update in your kodi for Matrix, just click update and you will be fine. 

Note: you might need to go to Matrix settings and delete thumbnails cache.

**Comment by mohamedsaad208** [comment]
It works thanks 👍

**Pull request merged**
